name: Hello World Workflow

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f3001761@ds.study.iitm.ac.in
        run: echo "hello world"
